/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import app.calculations.PhongRenderer;
import app.model.Material;
import app.model.MaterialFactory;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Piotr Pyśk
 */
public class ApplicationFrame extends JFrame {

    private final int w = 400;
    private final int h = 400;

    private PhongRenderer phong;
    private BufferedImage panelCopy;
    private Material mirror;
    private Material wood;
    private Material middle;

    public ApplicationFrame() {
        initComponents();
        panelCopy = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D graphics2D = panelCopy.createGraphics();
        graphics2D.setColor(Color.darkGray);
        graphics2D.fillOval(w / 2 - 150, h / 2 - 150, 300, 300);
        phong = new PhongRenderer();
        mirror = MaterialFactory.getInstance().getMirror();
        wood = MaterialFactory.getInstance().getWood();
        middle = MaterialFactory.getInstance().getIntermediate();

        refresh();
    }

    private void refresh() {
        sphere1.setIcon(new ImageIcon(phong.render(panelCopy, mirror)));
        sphere1.repaint();
//        sphere2.setIcon(new ImageIcon(phong.render(panelCopy, wood)));
//        sphere2.repaint();
//        sphere3.setIcon(new ImageIcon(phong.render(panelCopy, middle)));
//        sphere3.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sphere1 = new javax.swing.JLabel();
        sphere2 = new javax.swing.JLabel();
        sphere3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Model Phonga");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sphere1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sphere2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sphere3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sphere1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sphere2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sphere3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel sphere1;
    private javax.swing.JLabel sphere2;
    private javax.swing.JLabel sphere3;
    // End of variables declaration//GEN-END:variables
}
